In [2]:
import numpy as np

In [5]:
array1 = np.array([1,2,3,4,5,6])

print("Array 1D: ", array1)
print('Forma: ', array1.shape)
print('Tipo de datos: ', array1.dtype)

Array 1D:  [1 2 3 4 5 6]
Forma:  (6,)
Tipo de datos:  int32


In [6]:
array2 = array1.reshape((2,3))

print("Array 2D: ", array2)
print('Forma: ', array2.shape)
print('Tipo de datos: ', array2.dtype)

Array 2D:  [[1 2 3]
 [4 5 6]]
Forma:  (2, 3)
Tipo de datos:  int32


In [7]:
matrix = np.random.rand(4,4)

print("Array 2D: ", matrix)
print('Forma: ', matrix.shape)
print('Tipo de datos: ', matrix.dtype)

Array 2D:  [[0.92592775 0.93979315 0.28472041 0.61317305]
 [0.56424937 0.11210724 0.36161609 0.24694864]
 [0.42367407 0.02459979 0.69541353 0.87882836]
 [0.47494885 0.06508967 0.61387765 0.49579889]]
Forma:  (4, 4)
Tipo de datos:  float64


In [4]:
# crear un arreglo de 2 dimensiones a partir de una lista de listas

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr, type(arr)

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 numpy.ndarray)

In [5]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
arr = np.ones((2,2))
arr[1,1] = 10
arr

array([[ 1.,  1.],
       [ 1., 10.]])

In [8]:
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
# crear un arreglo 3d de ceros con forma 2,3,4

arr = np.zeros((2,3,4))
arr[0,1,2] = 5
arr

array([[[0., 0., 0., 0.],
        [0., 0., 5., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [11]:
arr = np.random.rand(2,5)
arr

array([[0.78752908, 0.27275284, 0.95304834, 0.58532022, 0.57478449],
       [0.69806596, 0.23733155, 0.65847567, 0.38830828, 0.58577787]])

In [12]:
arr.T

array([[0.78752908, 0.69806596],
       [0.27275284, 0.23733155],
       [0.95304834, 0.65847567],
       [0.58532022, 0.38830828],
       [0.57478449, 0.58577787]])

In [13]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

arr1, arr2

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [14]:
# concatenar arreglos horizontalmente

arr_h = np.hstack((arr1, arr2))
arr_h

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [16]:
# concatenar arreglos verticalmente

arr_v = np.vstack((arr1, arr2))
arr_v

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [18]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [19]:
suma = np.sum(arr)
suma

15

In [20]:
prom = np.mean(arr)
prom

3.0

In [21]:
mediana = np.median(arr)
mediana

3.0

In [22]:
producto = np.prod(arr)
producto

120

In [23]:
std =np.std(arr)
std

1.4142135623730951

In [24]:
varianza = np.var(arr)
varianza

2.0

In [25]:
min = np.min(arr)
max = np.max(arr)
min, max

(1, 5)

In [26]:
cumsum = np.cumsum(arr)
cumsum

array([ 1,  3,  6, 10, 15])

In [27]:
arr + arr

array([ 2,  4,  6,  8, 10])

In [28]:
arr - arr

array([0, 0, 0, 0, 0])

In [29]:
arr * arr

array([ 1,  4,  9, 16, 25])

In [30]:
arr / arr

array([1., 1., 1., 1., 1.])

### integracion de numpy y pandas

In [31]:
import pandas as pd
import numpy as np

In [34]:
data = np.array([[1,2,3],[4,5,6],[7,8,9]])

df = pd.DataFrame(data, columns=['A', 'B', 'C'])
df

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [35]:
data = {
    'A' : [1,4,7],
    'B' : [2,5,8],
    'C' : [3,6,9]
}

df = pd.DataFrame(data)
df

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [36]:
arr = df.to_numpy()
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int64)

In [37]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int64)

In [38]:
mean_columns = np.mean(df, axis=0)
mean_columns

A    4.0
B    5.0
C    6.0
dtype: float64

In [39]:
df.mean(axis=0)

A    4.0
B    5.0
C    6.0
dtype: float64

In [40]:
df.mean(axis=1)

0    2.0
1    5.0
2    8.0
dtype: float64